### ISSUE TITLE
Drawer menu problems

### ISSUE THREAD

**Issue by rsaccon** [developit/preact-mdl#4]
I am observing the following behavior with drawer menu: it works only as long we don't have a state change at the component which contains the Layout. The example below illustrates it, after 10 seconds the drawer hamburger button disappears  

```
componentDidMount() {
  setTimeout( () => this.setState({ foo: "bar" }), 10000);
}
```

In nectarine, you wire things up manually, maybe that is the way we are supposed to go. However in document viewer your drawer menu seems to work. Is there anything I am missing ?

**Comment by developit** [comment]
Personally I prefer to wire it up manually as in Nectarine (good hunting, sorry for the missing docs!).  Any time I'm relying on MDL to perform magical actions for me I get a bit worried.  I actually was afflicted by the disappearing hamburger menu in Documentation Viewer, but that was with an older version of Preact.  Are you running `3.2.0`?

**Comment by rsaccon** [comment]
@developit, yes, 3.2.0. Ok, then I will wire it up manually as well, that seems the best option for now.

**Comment by rsaccon** [comment]
I came up with the following work-around to make the drawer work on click of a custom menu button:

app component:

```
toggleDrawer() {
  var drawer = document.querySelector('.mdl-layout__drawer');
  var obfuscator = document.querySelector('.my-obfuscator');
  drawer.classList.toggle("is-visible");
  obfuscator.classList.toggle("is-visible");
}
```

```
<Layout fixed-header={true} fixed-drawer={false} class="mdl-layout--no-drawer-button">
  <Header />
  <Sidebar />
  <Main />
  <div class="my-obfuscator" onclick={this.toggleDrawer}></div>
</Layout>
```

Header Component then has a custom button (and access to the same `toggleDrawer()`)

```
<Layout.Header manual>
  <Layout.HeaderRow>
    <Button icon onClick={this.toggleDrawer}><Icon icon='menu' /></Button>
    <Layout.Title>My Title</Layout.Title>
  </Layout.HeaderRow>
</Layout.Header>
```

now comes the ugly part: `my-obfuscator` CSS class is an exact copy of the `mdl-layout__obfuscator`

if there is a better approach to get the drawer working, I love to hear.

React folks also do heavy hackery to get MDL running: https://tleunen.github.io/react-mdl/#/

**Comment by developit** [comment]
Often times for obfuscation, I actually just turn off pointer events and fade the non-sidebar elements.  This means either hooking something at the root of the page to close the menu or simply forgoing tap-to-close in the obfuscated area. Here's the technique in use on Nectarine:

``` css
.mdl-layout__drawer {
    &, & ~ * {
        transition: all 300ms ease;
    }
    &.is-visible ~ * {
        transform: translateX(240px/2);
        opacity: 0.1;
        pointer-events: none;
    }
}
```

ref: https://github.com/developit/nectarine/blob/master/src/style/index.less#L379-L387

---

These are the kinds of things I hope will get better as MDL improves. The amount of destructive things they do in order to avoid using pseudo elements is a little bit absurd, since their target supported browsers all support psuedos.

Another option I'm investigating is just porting or wrapping `react-toolbox` (you can already use it with [preact-compat](https://git.io/preact-compat), but I'd like an official version) or one of the other react material design libs.  For basic stuff like UI and styling, preact itself should be sufficiently similar to react in order to pull those things off.

**Comment by rsaccon** [comment]
@developit, react-toolbox looks interesting! Less strange JS stuff going on like at MDL. Ah, you already started with preact toolbox: https://github.com/developit/preact-toolbox

**Comment by developit** [comment]
I did yeah, though that was before it was possible to just use `preact-compat`. I'm hoping to get some time to look at it again soon.

**Comment by developit** [comment]
Closing this for now since I think the solution is to circumvent MDL.
