### ISSUE TITLE
TypeScript compilation errors

### ISSUE THREAD

**Issue by mbleigh** [developit/preact-mdl#41]
I'm getting:

```
node_modules/preact-mdl/dist/index.d.ts(12,41): error TS2314: Generic type 'ComponentProps<C>' requires 1 type argument(s).
node_modules/preact-mdl/dist/index.d.ts(13,34): error TS2314: Generic type 'ComponentProps<C>' requires 1 type argument(s).
node_modules/preact-mdl/dist/index.d.ts(15,31): error TS2314: Generic type 'ComponentProps<C>' requires 1 type argument(s).
```

This can be fixed by changing `preact.ComponentProps` to `preact.ComponentProps<any>` in the `.d.ts`.

1. Is this happening for everyone?
2. Should I just send a PR that fixes it with `<any>`?

**Comment by tschnoelzer** [comment]
same for me ... 

ERROR in /preact/preact-mdl-example/node_modules/preact-mdl/dist/index.d.ts
(12,41): error TS2314: Generic type 'ComponentProps<C>' requires 1 type argument(s).

ERROR in /preact/preact-mdl-example/node_modules/preact-mdl/dist/index.d.ts
(13,34): error TS2314: Generic type 'ComponentProps<C>' requires 1 type argument(s).

ERROR in /preact/preact-mdl-example/node_modules/preact-mdl/dist/index.d.ts
(15,31): error TS2314: Generic type 'ComponentProps<C>' requires 1 type argument(s).

when updating to 

    "preact": "^8.2.1",
    "preact-mdl": "^2.2.1",
    "preact-router": "^2.5.5",

with original files error due to missing FunctionalComponents .... so no luck at all...

**Comment by cvuorinen** [comment]
I also ran into this same issue after installing `preact-cli-plugin-typescript` to an existing `preact-cli` project that also uses `preact-mdl`.
